{
    "config": {
        "abort": {
            "already_configured": "Устройство уже сконфигурировано",
            "not_setup": "Интеграция не сконфигурирована"
        },
        "error": {
            "cannot_connect": "Ошибка при подключении. Проверьте правильность настроек",
            "unknown": "Неизвестная ошибка"
        },
        "step": {
            "user": {
                "data": {
                    "server": "Адрес LVT сервера",
                    "port": "Номер порта LVT API сервиса",
                    "password": "Пароль",
                    "not_in_use": "Недоступно при ручной конфигурации"
                }
            }
        }
    }
}